export const ALLOWED = new Set([
  'generate:component',
  'generate:page',
  'generate:hook',
  'generate:layout',
  'generate:service',
  'generate:style',
  'generate:test',
  'generate:context',
  'generate:store',
  'generate:env',
  'generate:middleware',
  'generate:api',
  'generate:config',
  // non-generator commands surfaced in chat mode
  'scan',
  'scan:init',
  'patch',
  'bump',
  'changelog',
  'completion',
  'mcp:serve',
  'rag:index',
  'rag:query'
]);
